# Cargo.toml
[package]
name = "rust‑worker‑simple"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
worker = "0.0.20"

[profile.release]
lto = true
strip = "debuginfo"
codegen-units = 1
